name: DevOps CI Pipeline

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

  docker-build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/calculator-app .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/calculator-app

      - name: Create build artifact
        run: zip -r build-package.zip .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-package
          path: build-package.zip
